# Generated by Django 2.1.2 on 2018-10-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tille',
            new_name='title',
        ),
    ]
